name: proyecto_nest_angular

services:
  db:
    image: postgres:14.3
    restart: always
    container_name: proyecto_nest_angular_db
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${USER_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data